[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  status = 200
  force = true
  to = "/.netlify/functions/api/:splat"